Fix AttributeError triggered by use of non-existent log_critical method in pcied (#33)
<!-- Provide a general summary of your changes in the Title above -->

#### Description
<!--
-->
This PR addresses a minor yet critical bug in the `pcied` daemon where an incorrect method call to `log.log_critical()` leads to an `AttributeError`, causing the daemon to crash during error handling.

The `Logger` class [`sonic_py_common/logger.py`](https://github.com/sonic-net/sonic-buildimage/blob/master/src/sonic-py-common/sonic_py_common/logger.py) used in `pcied` does not implement the method `log_critical()`. As a result, when Redis DB connection fails or PCIe utility loading fails (both edge-case scenarios), the exception handling code itself throws an `AttributeError`, which overrides the actual exception and crashes the daemon unexpectedly.

Python being an interpreted language, so such attribute errors in exception handling code remain hidden until the specific error scenario occurs. This explains why the issue has not surfaced in normal operation—since Redis connection failures or PCIe utility loading failures are rare.

#### Motivation and Context
<!--
 Why is this change required? What problem does it solve?
 If this pull request closes/resolves an open Issue, make sure you
 include the text "fixes #xxxx", "closes #xxxx" or "resolves #xxxx" here
-->
This change is required to prevent the `pcied` daemon from crashing during exception handling due to a call to a non-existent `log.log_critical()` method. By fixing this logging issue, the daemon will correctly log critical errors (like Redis DB or PCIe utility failures) without masking the root cause or terminating unexpectedly.

The logs before fix, if we simulate a Redis DB connection failure :
```
2025 Jul 25 19:07:09.306693 vlab-03 INFO pmon#supervisord: pcied During handling of the above exception, another exception occurred:
2025 Jul 25 19:07:09.306693 vlab-03 INFO pmon#supervisord: pcied
2025 Jul 25 19:07:09.306693 vlab-03 INFO pmon#supervisord: pcied Traceback (most recent call last):
2025 Jul 25 19:07:09.306693 vlab-03 INFO pmon#supervisord: pcied File "/usr/local/bin/pcied", line 342, in <module>
2025 Jul 25 19:07:09.306693 vlab-03 INFO pmon#supervisord: pcied sys.exit(main())
2025 Jul 25 19:07:09.306693 vlab-03 INFO pmon#supervisord: pcied ^^^^^^
2025 Jul 25 19:07:09.306693 vlab-03 INFO pmon#supervisord: pcied File "/usr/local/bin/pcied", line 330, in main
2025 Jul 25 19:07:09.306693 vlab-03 INFO pmon#supervisord: pcied pcied = DaemonPcied(SYSLOG_IDENTIFIER)
2025 Jul 25 19:07:09.306693 vlab-03 INFO pmon#supervisord: pcied ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025 Jul 25 19:07:09.306693 vlab-03 INFO pmon#supervisord: pcied File "/usr/local/bin/pcied", line 174, in __init__
2025 Jul 25 19:07:09.306693 vlab-03 INFO pmon#supervisord: pcied log.log_critical("Failed to connect to STATE_DB or create table. Error: {}".format(str(e)), True)
2025 Jul 25 19:07:09.306693 vlab-03 INFO pmon#supervisord: pcied ^^^^^^^^^^^^^^^^
2025 Jul 25 19:07:09.306693 vlab-03 INFO pmon#supervisord: pcied AttributeError: 'Logger' object has no attribute 'log_critical'
```

#### How Has This Been Tested?
<!--
 Please describe in detail how you tested your changes.
 Include details of your testing environment, and the tests you ran to
 see how your change affects other areas of the code, etc.
-->
Tested and verified in my local testbed
`tests/test_pcied.py::test_load_platform_pcieutil PASSED`

The fix is to replace the incorrect `log.log_critical()` calls with valid logger method `log.log_error()`

Note: In the below logs `Error: name 'logging' is not defined` is a way of simulating Redis db failure in the code and during handling of this exception, another exception `AttributeError` is thrown as shown above. In reality, the first exception can be anything related to Redis or PCIe utility and as shown below, its handled gracefully with the `AttributeError` no longer seen.

The logs after fix (Graceful handling of exception) :
```
2025 Jul 29 22:38:54.694836 vlab-01 NOTICE pmon#pcied: Failed to load platform Pcie module. Error : No module named 'sonic_platform', Fallback to default module
2025 Jul 29 22:38:54.717381 vlab-01 ERR pmon#CCmisApi: Failed to connect to STATE_DB or create table. Error: name 'logging' is not defined
2025 Jul 29 22:38:54.717704 vlab-01 WARNING pmon#CCmisApi: Exception during cleanup: 'DaemonPcied' object has no attribute 'status_table'
2025 Jul 29 22:38:54.717704 vlab-01 INFO pmon#supervisord: pcied Failed to load platform Pcie module. Error : No module named 'sonic_platform', Fallback to default module
2025 Jul 29 22:38:54.717704 vlab-01 INFO pmon#supervisord: pcied Failed to connect to STATE_DB or create table. Error: name 'logging' is not defined
2025 Jul 29 22:38:54.734308 vlab-01 INFO pmon#supervisord: pcied Exception during cleanup: 'DaemonPcied' object has no attribute 'status_table'
2025 Jul 29 22:38:54.745938 vlab-01 INFO pmon#supervisord 2025-07-29 22:38:54,742 WARN exited: pcied (exit status 1; not expected)
2025 Jul 29 22:38:55.751968 vlab-01 INFO pmon#supervisord 2025-07-29 22:38:55,746 INFO gave up: pcied entered FATAL state, too many start retries too quickly
```

#### Additional Information (Optional)